name: Transform NADS data and load to GS

on:
  workflow_dispatch:
  schedule:
    - cron: '25 20 * * 2,5'
permissions:
  contents: write

jobs:
  Get-NADS-Data-And-Transform:
    name: Get and transform NADS Data
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NADS_DASHB_SECRET: ${{ secrets.NADS_DASHB_SECRET }}
      
    steps:
    - name: Check out GH repository
      uses: actions/checkout@v4
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
        
    - name: Install libcurl and libssl on Linux
      run: 'sudo apt-get -y install libcurl4-openssl-dev'
      shell: bash
      
    - name: Install CRAN packages
      run: Rscript -e 'install.packages(c("tidyverse", "readxl", "googledrive", "googlesheets4"))'
    - name: Run NADS data transformation script
      run: Rscript "nads_dashboard_automation_gdrive_public.R"
